clone_depth: 1
version: '{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: if($env:appveyor_repo_tag -eq 'True') { Update-AppveyorBuild -Version $env:appveyor_repo_tag_name }
build_script:
  - cmd: dotnet pack Marugata.Game.Resources /p:Version=%APPVEYOR_BUILD_VERSION%
artifacts:
  - path: Marugata.Game.Resources/bin/Any CPU/Release/**/*.nupkg
deploy:
  - provider: Environment
    name: nuget
  - provider: Environment
    name: github